# Controller Persistent Volume Claim

# Home pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-home-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: {{ .Values.controller.homeCapacity }}
  selector: 
    matchLabels:
      name: cerebro-home-pv
---
# Checkpoint pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-checkpoint-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.controller.checkpointCapacity }}
  selector: 
    matchLabels:
      name: cerebro-checkpoint-pv
---
# Config pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-config-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.controller.configCapacity }}
  selector: 
    matchLabels:
      name: cerebro-config-pv
---
# Data pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cerebro-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: {{ .Values.controller.dataCapacity }}
  selector: 
    matchLabels:
      name: cerebro-data-pv